### ISSUE TITLE
An error is thrown using Safari (on Mac)

### ISSUE THREAD

**Issue by APEXGru** [mennooo/orclapex-ig-set-items#1] opened 2018-04-04 07:33 UTC
The error (running your demo page) is :
Error: Syntax error, unrecognized expression: label[for="P6_EMPNO"

Safari 11.1
MacOS High Sierra

Does work on Chrome or Firefox though. Great work!

**Comment by mennooo** [comment] 2018-04-04 09:03
Issue is caused by these lines:
https://github.com/mennooo/orclapex-ig-set-items/blob/bfe5ecea74e29b203799df86137115e8a249839f/server/js/IGSetItems.js#L10

https://github.com/mennooo/orclapex-ig-set-items/blob/bfe5ecea74e29b203799df86137115e8a249839f/server/js/IGSetItems.js#L15

A square closing bracket is missing.

**Closed as completed** 2018-04-04 18:29 UTC
Labels: bug
